import { z } from 'zod';
import { defineTool } from '../Tool.js';

export const briefTool = defineTool({
  name: 'brief',
  description: '生成当前会话的简要总结。包括对话主题、已使用的工具、关键决策等。',
  inputSchema: z.object({
    detail: z.enum(['brief', 'normal', 'detailed']).optional().describe('详细程度'),
  }),
  isReadOnly: true,
  isConcurrencySafe: true,
  searchHint: 'brief summary overview session recap',
  async call(input, ctx) {
    const { detail = 'normal' } = input as { detail?: string };
    return { data: '[Brief summary will be generated by AI based on conversation context]' };
  },
});
